title: David Rothschild 
description: My Tech Blog/Portfolio
author: David Rothschild
logo: 
github: https://github.com/drothschild
about: Software Engineer

baseurl: 
url: 

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
